#!/usr/bin/env python

import sys
import cv2
import numpy
import os.path

input_path = sys.argv[1]
output_path = sys.argv[2]

if(not os.path.isfile(input_path)):
    print("Error! Could not find image at " + input_path)
    exit(2)

if(output_path[-1] != '/'):
    output_path = output_path + '/'

original_img = cv2.imread(input_path)

try:
    decoded = cv2.imdecode(original_img, 1)
except Exception as e:
    print("Error! Could not decode image at " + input_path + ":\n" + str(e))
    exit(3)

print("Writing images to " + output_path)
cv2.imwrite(output_path + "regular.jpg", original_img)
